"""phase 3 update

Revision ID: 850660cc9a2e
Revises: 
Create Date: 2021-06-16 21:11:43.734057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850660cc9a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=True)
    op.add_column('user', sa.Column('dark_theme', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('private_profile', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('instagram_post_visibility', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('private_articles', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'private_articles')
    op.drop_column('user', 'instagram_post_visibility')
    op.drop_column('user', 'private_profile')
    op.drop_column('user', 'dark_theme')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
