"""phase 2 update

Revision ID: e85ebc40ac99
Revises: 
Create Date: 2021-06-10 20:13:23.289284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85ebc40ac99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_post_id'), 'instagram_post', ['id'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_instagram_post_id'), table_name='instagram_post')
    op.drop_table('instagram_post')
    # ### end Alembic commands ###
